apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx  # Ensure this namespace exists before applying
spec:
  replicas: 2  # Fixed: 'replica' → should be 'replicas'
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx  # Corrected indentation
        image: nginx:latest
        ports:
        - containerPort: 80  # Corrected indentation

